"use client";
import React from 'react';
import { Clock, CheckCircle, XCircle } from 'lucide-react';

/**
 * DailyBlueprintTimeline component (Phase 1 Placeholder)
 * This component will eventually display the unified schedule generated by the plannerLogic.
 */
export default function DailyBlueprintTimeline({ blueprintData }) {
  // Use mock data or the data fetched from the /api/planner/blueprint route
  const mockBlueprint = blueprintData || [
    { time: "07:00", name: "Fixed Routine: Wake Up & Exercise", type: "routine", status: "completed" },
    { time: "10:00", name: "Fixed Class: CS 301 Lecture", type: "routine", status: "pending" },
    { time: "14:00", name: "Academic Task: Study Math (Micro-Goal 1/3)", type: "task", duration: 90, status: "pending" },
    { time: "15:30", name: "Routine: Coffee Break", type: "routine", status: "pending" },
  ];

  const StatusIcon = ({ status }) => {
    switch (status) {
      case 'completed': return <CheckCircle className="h-5 w-5 text-green-500" />;
      case 'pending': return <Clock className="h-5 w-5 text-yellow-500" />;
      case 'slipped': return <XCircle className="h-5 w-5 text-red-500" />;
      default: return null;
    }
  };

  return (
    <div className="space-y-4">
      <h3 className="text-xl font-semibold border-b pb-2 text-gray-800 dark:text-white">
        Today's Blueprint ({new Date().toDateString()})
      </h3>
      {mockBlueprint.map((item, index) => (
        <div 
          key={index} 
          className={`flex items-center space-x-4 p-4 rounded-xl shadow-sm transition-all ${
            item.type === 'task' 
              ? 'bg-emerald-50 dark:bg-emerald-900/20 border-l-4 border-emerald-500' 
              : 'bg-gray-50 dark:bg-gray-700/50 border-l-4 border-gray-300'
          }`}
        >
          <div className="flex-shrink-0">
            <StatusIcon status={item.status} />
          </div>
          <div className="flex-grow">
            <p className="font-medium text-gray-900 dark:text-white">{item.name}</p>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              {item.time} {item.duration ? `(${item.duration} min)` : ''}
            </p>
          </div>
          {item.status === 'pending' && item.type === 'task' && (
            <button className="text-sm text-emerald-600 hover:text-emerald-700 font-medium whitespace-nowrap">
              Start Now
            </button>
          )}
        </div>
      ))}
      <div className="pt-4 text-center">
        <p className="text-gray-500 dark:text-gray-400">
          This view combines your routines and scheduled study blocks.
        </p>
      </div>
    </div>
  );
}