// app/ai/notes/page.js
"use client";

import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useState, useEffect, useRef } from "react";
import { 
  Loader2, Sparkles, Zap, BatteryCharging, 
  ExternalLink, AlertCircle, CheckCircle2, 
  Download, FileJson, FileText, Clipboard,
  ChevronDown, BookOpen
} from "lucide-react";
import Link from "next/link";
import toast from "react-hot-toast";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";
import { saveAs } from "file-saver";
import mermaid from "mermaid";

export default function AINotesPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const notesRef = useRef(null);
  const outputRef = useRef(null);
  
  const [loading, setLoading] = useState(true);
  const [content, setContent] = useState("");
  const [notes, setNotes] = useState("");
  const [generating, setGenerating] = useState(false);
  const [creditsRemaining, setCreditsRemaining] = useState(0);
  const [isUnlimited, setIsUnlimited] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    mermaid.initialize({ 
      startOnLoad: true,
      theme: 'dark',
      themeVariables: {
        primaryColor: '#06b6d4',
        primaryTextColor: '#fff',
        primaryBorderColor: '#a855f7',
        lineColor: '#06b6d4',
        secondaryColor: '#7c3aed',
        tertiaryColor: '#1e293b'
      }
    });
  }, []);

  const fetchCredits = async () => {
    try {
      const res = await fetch("/api/user/credits");
      if (res.ok) {
        const data = await res.json();
        setCreditsRemaining(data.available || 0);
        setIsUnlimited(data.plan === 'Premium' || data.plan === 'Pro Max');
      }
    } catch (err) {
      console.error("Failed to fetch credits:", err);
    }
  };

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/auth");
    } else if (status === "authenticated") {
      fetchCredits();
      setLoading(false);
    }
  }, [status, router]);

  // Render mermaid diagrams after notes update
  useEffect(() => {
    if (notes) {
      setTimeout(() => {
        mermaid.contentLoaded();
      }, 100);
      // Smooth scroll to output
      if (outputRef.current) {
        outputRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }
  }, [notes]);

  // --- EXPORT FUNCTIONS ---

  const exportPDF = async () => {
    const element = notesRef.current;
    if (!element) return;
    const loadingToast = toast.loading("Preparing PDF...");
    
    try {
      const canvas = await html2canvas(element, { 
        scale: 2, 
        backgroundColor: "#0f172a",
        useCORS: true 
      });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
      pdf.save("AI_Synthesized_Notes.pdf");
      toast.success("PDF Downloaded!");
    } catch (err) {
      toast.error("PDF export failed.");
    } finally {
      toast.dismiss(loadingToast);
    }
  };

  const exportDocx = async () => {
    const loadingToast = toast.loading("Generating Professional Document...");
    try {
      const lines = notes.split('\n').filter(l => l.trim());
      const children = [];

      // Title Page
      children.push(
        new Paragraph({
          children: [
            new TextRun({ 
              text: "SYNTHESIZED NOTES", 
              bold: true, 
              size: 48, 
              color: "2E86C1",
              font: "Garamond"
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [
            new TextRun({ 
              text: "Generated by StudySync AI", 
              size: 24, 
              color: "7F8C8D",
              italics: true,
              font: "Garamond"
            }),
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 800 },
        })
      );

      // Content with LaTeX-style formatting
      lines.forEach(line => {
        const trimmed = line.trim();
        
        if (trimmed.startsWith('# ')) {
          children.push(new Paragraph({
            children: [new TextRun({ 
              text: trimmed.substring(2), 
              bold: true, 
              size: 32,
              color: "1A5490",
              font: "Garamond"
            })],
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
            border: {
              bottom: {
                color: "2E86C1",
                space: 1,
                value: BorderStyle.SINGLE,
                size: 6,
              }
            }
          }));
        } else if (trimmed.startsWith('## ')) {
          children.push(new Paragraph({
            children: [new TextRun({ 
              text: trimmed.substring(3), 
              bold: true, 
              size: 28,
              color: "2874A6",
              font: "Garamond"
            })],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 150 }
          }));
        } else if (trimmed.startsWith('### ')) {
          children.push(new Paragraph({
            children: [new TextRun({ 
              text: trimmed.substring(4), 
              bold: true, 
              size: 24,
              color: "5DADE2",
              font: "Garamond"
            })],
            heading: HeadingLevel.HEADING_3,
            spacing: { before: 200, after: 100 }
          }));
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          children.push(new Paragraph({
            children: [new TextRun({ 
              text: '• ' + trimmed.substring(2), 
              size: 22,
              font: "Garamond"
            })],
            spacing: { before: 100, after: 100 },
            indent: { left: 720 }
          }));
        } else if (trimmed) {
          children.push(new Paragraph({
            children: [new TextRun({ 
              text: trimmed, 
              size: 22,
              font: "Garamond"
            })],
            spacing: { before: 150, after: 150 },
            alignment: AlignmentType.JUSTIFIED
          }));
        }
      });

      const doc = new Document({
        sections: [{
          properties: {
            page: {
              margin: {
                top: 1440,
                right: 1440,
                bottom: 1440,
                left: 1440,
              }
            }
          },
          children
        }],
      });

      const blob = await Packer.toBlob(doc);
      saveAs(blob, "Professional_AI_Notes.docx");
      toast.success("Professional document downloaded!");
    } catch (err) {
      toast.error("Word export failed.");
    } finally {
      toast.dismiss(loadingToast);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(notes);
    toast.success("Copied to clipboard!");
  };

  const generateNotes = async () => {
    if (!content.trim()) {
      toast.error("Please enter some content");
      return;
    }
    setGenerating(true);
    setError("");
    const loadingToast = toast.loading("AI is synthesizing your data...");

    try {
      const response = await fetch("/api/ai/notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });

      const data = await response.json();
      toast.dismiss(loadingToast);

      if (!response.ok) {
        setError(data.error || "Generation failed");
        return;
      }

      setNotes(data.notes || "");
      if (data.credits) {
        setCreditsRemaining(data.credits.remaining);
        setIsUnlimited(data.credits.isUnlimited);
      }
      toast.success("Synthesis Successful!");
    } catch (err) {
      toast.dismiss(loadingToast);
      setError("Network fault: " + err.message);
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-950">
        <Loader2 className="h-10 w-10 animate-spin text-cyan-400" />
      </div>
    );
  }

  const lowCredit = !isUnlimited && creditsRemaining < 3;

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-slate-900 to-gray-950 text-white font-sans py-12 px-4 sm:px-6 lg:px-8">
      {/* Add KaTeX CSS */}
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css"
        integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC"
        crossOrigin="anonymous"
      />
      
      <div className="max-w-6xl mx-auto">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-10 gap-6 border-b border-cyan-500/20 pb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <Sparkles className="text-purple-400 h-8 w-8 animate-pulse" />
              <h1 className="text-4xl font-black tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-blue-400 to-purple-500">
                STUDYSYNC AI NOTES
              </h1>
            </div>
            <p className="text-gray-400 font-mono text-sm">V2.0 // NEURAL SYNTHESIS ENGINE // ENHANCED TYPOGRAPHY</p>
          </div>

          <div className={`flex items-center gap-4 px-6 py-3 rounded-2xl border ${
            lowCredit ? 'border-red-500/50 bg-red-950/20' : 'border-cyan-500/30 bg-cyan-950/20'
          }`}>
            <BatteryCharging className={lowCredit ? 'text-red-400' : 'text-cyan-400'} />
            <span className="font-mono font-bold tracking-widest">
              {isUnlimited ? 'UNLIMITED' : `POWER: ${creditsRemaining}`}
            </span>
          </div>
        </div>

        {/* Input Section - Full Width */}
        <div className="mb-10">
          <div className="bg-gradient-to-br from-gray-900/60 to-gray-900/40 border border-cyan-500/20 rounded-3xl p-8 backdrop-blur-md shadow-2xl shadow-cyan-500/10">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-cyan-400 font-mono text-sm uppercase tracking-[0.3em] flex items-center gap-2">
                <span className="w-2 h-2 bg-cyan-400 rounded-full animate-pulse"></span>
                Source Data Input
              </h2>
              <div className="flex items-center gap-2 text-xs text-gray-500">
                <BookOpen size={14} />
                <span>Accepts: Articles, Transcripts, Notes, PDFs</span>
              </div>
            </div>
            
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Paste your content here... (articles, video transcripts, lecture notes, research papers)&#10;&#10;💡 Tip: Request 'create diagrams', 'include flowchart', or 'add formulas' for enhanced visualizations!"
              className="w-full h-[300px] bg-slate-950/60 border border-gray-700/50 rounded-2xl p-6 text-gray-200 focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all font-mono text-sm leading-relaxed resize-none"
            />
            
            <div className="flex items-center justify-between mt-6">
              <div className="text-xs text-gray-600">
                {content.length > 0 && `${content.length} characters • ~${Math.ceil(content.split(/\s+/).length)} words`}
              </div>
              
              <button
                onClick={generateNotes}
                disabled={generating || !content.trim()}
                className="px-8 py-4 rounded-2xl bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-600 hover:from-cyan-400 hover:via-blue-400 hover:to-purple-500 font-bold text-lg shadow-xl shadow-purple-500/30 transition-all flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-[1.02] active:scale-[0.98]"
              >
                {generating ? (
                  <>
                    <Loader2 className="animate-spin" size={22} />
                    SYNTHESIZING...
                  </>
                ) : (
                  <>
                    <Zap size={22} />
                    START AI SYNTHESIS
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Output Section - Full Width Below Input */}
        {notes && (
          <div ref={outputRef} className="animate-fadeIn">
            {/* Export Actions Bar */}
            <div className="flex items-center justify-between mb-6 px-4">
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 bg-emerald-500 rounded-full animate-pulse"></div>
                <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-purple-500">
                  Your Synthesized Document
                </h2>
              </div>
              
              <div className="flex gap-3">
                <button 
                  onClick={copyToClipboard} 
                  className="flex items-center gap-2 px-4 py-2 bg-gray-800/50 hover:bg-gray-700/50 border border-gray-700 rounded-xl text-gray-300 transition-all hover:scale-105"
                  title="Copy to Clipboard"
                >
                  <Clipboard size={18} />
                  <span className="text-sm font-medium">Copy</span>
                </button>
                <button 
                  onClick={exportPDF} 
                  className="flex items-center gap-2 px-4 py-2 bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl text-sm font-bold hover:bg-red-500/20 hover:border-red-500/50 transition-all hover:scale-105"
                >
                  <FileText size={18} /> Export PDF
                </button>
                <button 
                  onClick={exportDocx} 
                  className="flex items-center gap-2 px-4 py-2 bg-blue-500/10 border border-blue-500/30 text-blue-400 rounded-xl text-sm font-bold hover:bg-blue-500/20 hover:border-blue-500/50 transition-all hover:scale-105"
                >
                  <FileJson size={18} /> Export DOCX
                </button>
              </div>
            </div>

            {/* Beautiful Document Display */}
            <div className="bg-gradient-to-br from-slate-900/80 to-slate-800/60 border border-purple-500/20 rounded-3xl p-12 md:p-16 backdrop-blur-md shadow-2xl shadow-purple-500/20">
              <div 
                ref={notesRef} 
                className="academic-document max-w-4xl mx-auto"
                style={{
                  fontFamily: "'Crimson Text', 'Georgia', 'Times New Roman', serif",
                  fontSize: '18px',
                  lineHeight: '1.9',
                  color: '#e2e8f0'
                }}
              >
                <ReactMarkdown
                  remarkPlugins={[remarkGfm, remarkMath]}
                  rehypePlugins={[rehypeKatex]}
                  components={{
                    h1: ({node, ...props}) => (
                      <h1 
                        style={{
                          fontSize: '3rem',
                          fontWeight: '700',
                          marginTop: '3rem',
                          marginBottom: '2rem',
                          background: 'linear-gradient(to right, #06b6d4, #a855f7)',
                          WebkitBackgroundClip: 'text',
                          WebkitTextFillColor: 'transparent',
                          borderBottom: '4px solid rgba(6, 182, 212, 0.4)',
                          paddingBottom: '1rem',
                          letterSpacing: '-0.02em',
                          textAlign: 'center'
                        }} 
                        {...props} 
                      />
                    ),
                    h2: ({node, ...props}) => (
                      <h2 
                        style={{
                          fontSize: '2.25rem',
                          fontWeight: '600',
                          marginTop: '2.5rem',
                          marginBottom: '1.25rem',
                          color: '#7dd3fc',
                          borderLeft: '6px solid #06b6d4',
                          paddingLeft: '1.5rem',
                          letterSpacing: '-0.01em'
                        }} 
                        {...props} 
                      />
                    ),
                    h3: ({node, ...props}) => (
                      <h3 
                        style={{
                          fontSize: '1.75rem',
                          fontWeight: '600',
                          marginTop: '2rem',
                          marginBottom: '1rem',
                          color: '#c4b5fd',
                          letterSpacing: '-0.01em'
                        }} 
                        {...props} 
                      />
                    ),
                    p: ({node, ...props}) => (
                      <p 
                        style={{
                          marginBottom: '1.5rem',
                          textAlign: 'justify',
                          textJustify: 'inter-word',
                          color: '#cbd5e1',
                          lineHeight: '2',
                          fontSize: '1.1rem'
                        }} 
                        {...props} 
                      />
                    ),
                    ul: ({node, ...props}) => (
                      <ul 
                        style={{
                          marginLeft: '2rem',
                          marginBottom: '1.5rem',
                          listStyleType: 'none'
                        }} 
                        {...props} 
                      />
                    ),
                    li: ({node, ...props}) => (
                      <li 
                        style={{
                          marginBottom: '0.75rem',
                          paddingLeft: '2rem',
                          position: 'relative',
                          color: '#cbd5e1',
                          fontSize: '1.05rem'
                        }}
                        {...props}
                      >
                        <span style={{
                          position: 'absolute',
                          left: '0',
                          color: '#06b6d4',
                          fontWeight: 'bold',
                          fontSize: '1.2rem'
                        }}>▸</span>
                        {props.children}
                      </li>
                    ),
                    blockquote: ({node, ...props}) => (
                      <blockquote 
                        style={{
                          borderLeft: '5px solid #a855f7',
                          paddingLeft: '2rem',
                          paddingTop: '1rem',
                          paddingBottom: '1rem',
                          marginLeft: '0',
                          marginBottom: '2rem',
                          fontStyle: 'italic',
                          background: 'rgba(168, 85, 247, 0.08)',
                          borderRadius: '0 12px 12px 0',
                          color: '#e9d5ff',
                          fontSize: '1.05rem'
                        }} 
                        {...props} 
                      />
                    ),
                    code: ({node, inline, ...props}) => inline ? (
                      <code 
                        style={{
                          background: 'rgba(6, 182, 212, 0.15)',
                          padding: '0.25rem 0.5rem',
                          borderRadius: '6px',
                          fontSize: '0.95em',
                          fontFamily: "'Fira Code', 'Courier New', monospace",
                          color: '#67e8f9',
                          border: '1px solid rgba(6, 182, 212, 0.3)'
                        }} 
                        {...props} 
                      />
                    ) : (
                      <code 
                        style={{
                          display: 'block',
                          background: 'rgba(15, 23, 42, 0.9)',
                          padding: '1.5rem',
                          borderRadius: '12px',
                          fontSize: '0.95em',
                          fontFamily: "'Fira Code', 'Courier New', monospace",
                          color: '#67e8f9',
                          border: '1px solid rgba(6, 182, 212, 0.3)',
                          overflowX: 'auto',
                          marginBottom: '1.5rem'
                        }} 
                        {...props} 
                      />
                    ),
                    strong: ({node, ...props}) => (
                      <strong 
                        style={{
                          fontWeight: '700',
                          color: '#fbbf24'
                        }} 
                        {...props} 
                      />
                    ),
                    em: ({node, ...props}) => (
                      <em 
                        style={{
                          fontStyle: 'italic',
                          color: '#c4b5fd'
                        }} 
                        {...props} 
                      />
                    ),
                    table: ({node, ...props}) => (
                      <div style={{ overflowX: 'auto', marginBottom: '2rem', marginTop: '2rem' }}>
                        <table 
                          style={{
                            width: '100%',
                            borderCollapse: 'collapse',
                            border: '2px solid rgba(6, 182, 212, 0.4)',
                            borderRadius: '8px',
                            overflow: 'hidden'
                          }} 
                          {...props} 
                        />
                      </div>
                    ),
                    th: ({node, ...props}) => (
                      <th 
                        style={{
                          background: 'rgba(6, 182, 212, 0.2)',
                          padding: '1rem',
                          border: '1px solid rgba(6, 182, 212, 0.3)',
                          fontWeight: '700',
                          color: '#7dd3fc',
                          textAlign: 'left',
                          fontSize: '1.05rem'
                        }} 
                        {...props} 
                      />
                    ),
                    td: ({node, ...props}) => (
                      <td 
                        style={{
                          padding: '1rem',
                          border: '1px solid rgba(6, 182, 212, 0.2)',
                          color: '#cbd5e1',
                          fontSize: '1.05rem'
                        }} 
                        {...props} 
                      />
                    ),
                    hr: ({node, ...props}) => (
                      <hr 
                        style={{
                          border: 'none',
                          height: '3px',
                          background: 'linear-gradient(to right, transparent, rgba(6, 182, 212, 0.6), transparent)',
                          margin: '3rem 0'
                        }} 
                        {...props} 
                      />
                    ),
                  }}
                >
                  {notes}
                </ReactMarkdown>
              </div>

              {/* Document Footer */}
              <div className="mt-12 pt-8 border-t border-gray-700/30 flex items-center justify-center gap-3 text-emerald-400 font-mono text-xs uppercase tracking-wider">
                <CheckCircle2 size={16} className="animate-pulse" /> 
                Document Synthesis Complete • AI Verified • Ready for Export
              </div>
            </div>
          </div>
        )}

        {/* Empty State When No Notes */}
        {!notes && !generating && (
          <div className="mt-12 bg-gradient-to-br from-slate-900/40 to-slate-800/30 border border-gray-700/30 rounded-3xl p-16 backdrop-blur-md">
            <div className="flex flex-col items-center justify-center text-center space-y-6 max-w-2xl mx-auto">
              <div className="relative">
                <Sparkles size={80} className="opacity-20 text-cyan-400" />
                <div className="absolute inset-0 blur-2xl bg-cyan-500/10 animate-pulse"></div>
              </div>
              <h3 className="text-2xl font-bold text-gray-400">Your AI-Generated Document Will Appear Here</h3>
              <p className="text-gray-500 leading-relaxed max-w-lg">
                Enter your content above and click "Start AI Synthesis" to generate beautifully formatted notes with diagrams, formulas, and academic styling. The output will be displayed in a stunning full-page format below.
              </p>
              <div className="flex items-center gap-2 text-cyan-400/50">
                <ChevronDown size={24} className="animate-bounce" />
                <span className="text-sm font-mono">Awaiting your input</span>
              </div>
            </div>
          </div>
        )}

      </div>

      <style jsx global>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .animate-fadeIn {
          animation: fadeIn 0.6s ease-out;
        }

        .academic-document .katex {
          font-size: 1.15em;
        }

        .academic-document .katex-display {
          margin: 2rem 0;
          padding: 1.5rem;
          background: rgba(6, 182, 212, 0.08);
          border-radius: 12px;
          border: 2px solid rgba(6, 182, 212, 0.25);
        }

        @import url('https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400&display=swap');
      `}</style>
    </div>
  );
}
